### PR TITLE
Adding a pop-up on subscribing to newsletter

### PR DESCRIPTION
**Pull request by Aniruddhmuley2001**
# Description
Adding a pop-up box, which will appear on clicking the submit button of subscription to the newsletter. This will make the website more interactive with the user.

# Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented on my code or provided relevant documentation, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by anubhavsingh16** [comment]
@Aniruddhmuley2001  What is Stay Tuned `&#128522;`!!?

**Comment by Aniruddhmuley2001** [comment]
The expression is to add a smile emoji, in HTML (alert message). Here, stay tuned with a smile emoji will help the website engage more with the ones who have subscribed to the newsletter.

**Comment by Aniruddhmuley2001** [comment]
@anubhavsingh16  Just check it once again, since I feel the emoji code is not working. If so, I will correct it in another pull request.

**Comment by anubhavsingh16** [comment]
Yes emoji is not working @Aniruddhmuley2001

**Comment by Aniruddhmuley2001** [comment]
@anubhavsingh16 Have created another pull request. Just check it out once

**Comment by anubhavsingh16** [comment]
okk

**Pull request merged**
