### PR TITLE
Added Margin to avoid overlapping of month with footer in mobile view 

### LINKED ISSUE #123: Third month overlapping with footer in mobile view
The third month is overlapping with the footer in mobile view. Can I fix this issue?
issue

### PR DESCRIPTION
**Pull request by aastha985**
Fixes #123 

# Type of Change:
- Code
- User Interface

# Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

### CODE REVIEW

**Comment by Lordtien** [comment]
@aastha985 Adding a screenshot in the PR description as done in the issue to show the fix might be a good idea.

**Comment by anubhavsingh16** [comment]
Yes @Lordtien you are right.
@aastha985 please try to add screenshots from next time when you send PR for UI.

**Comment by anubhavsingh16** [comment]
@aashimgarg please review this PR.

**Comment by aastha985** [comment]
@anubhavsingh16 @Lordtien Sure, I'll take care of this.

**Pull request merged**
