### PR TITLE
Contact form validation added

### PR DESCRIPTION
**Pull request by swarajpure**
# Description
Added contact form validation.
Name: Accepts only alphabets
Email: Accepts only email ID
Number: Accepts only number (max 15 digits)
Message: Accepts characters (max 100)

Cleaned the code using Prettier.

image
image
image

# Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by anubhavsingh16** [comment]
Focus on UI.

**Comment by swarajpure** [comment]
> 
> 
> 😢 What do you want bro?

What happened?

**Comment by aryamanpuri** [comment]
Please link to which issue you are working that makes easy for all the maintainers to review work.

**Comment by swarajpure** [comment]
> 
> 
> Please link to which issue you are working that makes easy for all the maintainers to review work.

Will keep it in mind next year.
Someone please look after this PR and let me know if there are any problems. Its been almost 24hours and I got no response yet. This is quite discouraging honestly.

**Comment by aryamanpuri** [comment]
We were having that discussion about this pr in the background

**Pull request merged**
